FROM ubuntu:18.04

# DEPENDENCIES
RUN apt-get update &&\
    apt-get -y install wget unzip build-essential cmake git pkg-config libgtk-3-dev \
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev \
    gfortran openexr libatlas-base-dev python3-dev python3-numpy \
    libtbb2 libtbb-dev libdc1394-22-dev libc6 libc6-dev

# BUILD AND INSTALL OPENCV AND OPENCV CONTRIB
ENV OPENCV_VERSION="4.6.0"
WORKDIR /opencv-src
RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip &&\
    wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.zip &&\
    unzip opencv.zip && mv opencv-${OPENCV_VERSION} opencv &&\
    unzip opencv_contrib.zip && mv opencv_contrib-${OPENCV_VERSION} opencv_contrib &&\
    mkdir opencv/build && cd opencv/build &&\
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D OPENCV_EXTRA_MODULES_PATH=/opencv-src/opencv_contrib/modules \
        -D WITH_OPENMP=ON \
        -D BUILD_TIFF=ON \
        -D WITH_FFMPEG=ON \
        -D WITH_GSTREAMER=ON \
        -D WITH_TBB=ON \
        -D BUILD_TBB=ON \
        -D BUILD_TESTS=OFF \
        -D WITH_EIGEN=OFF \
        -D WITH_V4L=ON \
        -D WITH_LIBV4L=ON \
        -D WITH_VTK=OFF \
        -D WITH_JASPER=OFF \
        -D OPENCV_EXTRA_EXE_LINKER_FLAGS=-latomic \
        -D OPENCV_ENABLE_NONFREE=ON \
        -D INSTALL_C_EXAMPLES=OFF \
        -D INSTALL_PYTHON_EXAMPLES=OFF \
        -D BUILD_NEW_PYTHON_SUPPORT=ON \
        -D BUILD_opencv_python3=ON \
        -D HAVE_opencv_python3=ON \
        -D PYTHON_DEFAULT_EXECUTABLE=$(which python3) \
        -D BUILD_opencv_python3=TRUE \
        -D OPENCV_GENERATE_PKGCONFIG=ON \
        -D BUILD_EXAMPLES=OFF .. &&\
    make -j$(grep -c ^processor /proc/cpuinfo) &&\
    make install &&\
    ldconfig &&\
    rm -rf /opencv-src

# BUILD AND INSTALL OPENCVSHARP
ENV OPENCV_SHARP_VERSION="4.6.0.20220608"
WORKDIR /opencvsharp-src
RUN git clone https://github.com/shimat/opencvsharp.git /opencvsharp-src &&\
    git fetch --all --tags --prune && git checkout ${OPENCV_SHARP_VERSION} &&\
    mkdir src/build && cd src/build &&\
    cmake -D CMAKE_INSTALL_PREFIX=/usr/local .. &&\
    make -j$(grep -c ^processor /proc/cpuinfo) &&\
    make install &&\
    ldconfig &&\
    cp OpenCvSharpExtern/libOpenCvSharpExtern.so /usr/lib &&\
    rm -rf /opencvsharp-src

CMD /bin/sh
