name: Docker mcr.microsoft.com/dotnet/sdk:6.0-focal

on:
  pull_request:
    types: [synchronize, opened]

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      - name: docker build
        run: |
          docker build -t lwq/ubuntu18-dotnet6sdk-opencv4.6.0 .
